name: Share data between jobs

on: [push]

env:

  basic: 40000

jobs:
  job_1:
    name: Add DA
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr $basic + $basic * 0.20  > pay.txt
      - name: Upload pay result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: account
          path: pay.txt

  job_2:
    name: Deducting PF
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download pay result for job 1
        uses: actions/download-artifact@v3
        with:
          name: account
      - shell: bash
        run: |
          value=`cat pay.txt`
          expr $value - 40000 * .12  > pay.txt
      - name: Upload pay result for job 2
        uses: actions/upload-artifact@v3
        with:
          name: account
          path: pay.txt

  job_3:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Download pay result for job 2
        uses: actions/download-artifact@v3
        with:
          name: account
      - name: Print the final result
        shell: bash
        run: |
          value=`cat pay.txt`
          echo The result is $value
