# This is a basic workflow to help you get started with Actions

name: DataSharing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  username: Devops Trainer
  super_duper_var: totally_awesome
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - shell: bash
        run: |
             username > output.log
             date > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
    
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
